### ISSUE TITLE
Provide settings to monitor smoothie charts

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux_ui#8]
Smoothie.js has many options. It would be nice to be able to specify/override these from the graph yaml for the ui node.

**Comment by mesca** [comment]
That was on the todo list, but we won't add new features on the current version of the monitoring interface. We want to replace smoothie by something that is able to use the GPU for faster rendering. There was a POC [here](https://github.com/mesca/sensorchart), but I never found the time to integrate the library with Timeflux. It has been two years since the initial release of SensorChart, so I need to reevaluate options such as [stackgl](http://stack.g). Also, we will rewrite the UI to make it more modular, so we can have several widgets for different types of visualizations.
